### ISSUE TITLE
Emulated mouse button order changed compared with deprecated libretro dosbox port

### ISSUE THREAD

**Issue by morlenxus** [libretro/dosbox-svn#61]
Hey,

first at all, dosbox-svn works really great for me. Still i have an issue with the emulated mouse which pre-assign the left and right mouse buttons to my ps3 controller. Both are at the lower trigger buttons L2 and R2, which seems to be a little unhandy. Could you rechange that to the L1 and R1 buttons?

Thanks,
Brian

**Comment by realnc** [comment]
Since April, emulated mouse buttons are assigned to L1/R1, not L2/R2. However, these are the default assignments. If you have a input config saved already, then you're still using the old defaults.

(As a side-note, [DOSBox-core](https://github.com/realnc/dosbox-core#dosbox-core) is the modern DOS core. Try that if your platform supports it. It's in the RA core downloader.)

**Comment by morlenxus** [comment]
> Since April, emulated mouse buttons are assigned to L1/R1, not L2/R2. However, these are the default assignments. If you have a input config saved already, then you're still using the old defaults.
Thanks, i'm checking that.
> (As a side-note, [DOSBox-core](https://github.com/realnc/dosbox-core#dosbox-core) is the modern DOS core. Try that if your platform supports it. It's in the RA core downloader.)
I'm confused, there is dosbox, dosbox-svn and also dosbox-core? Which one should i use on rp3/4 and why do different cores exists? :)

**Comment by realnc** [comment]
There's only two active cores: DOSBox-core and DOSBox-svn. All the others are dead. They're still included in the RA updater because... reasons? I don't know. They're dead, buggy and nobody is maintaining them, they have received no updates for ages.

DOSBox-SVN is the "legacy" core. It's there to support systems like the PS Vita, macOS older than 10.13, etc. DOSBox-core on the other hand is targetting more modern systems. If it's available on your system, then it's the recommended core.

**Comment by morlenxus** [comment]
Thanks! I'm giving the dosbox-core a try...
